# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=200)),
                ('registrationdeadline', models.DateField(default=datetime.date.today, verbose_name='Sichtbar bis einschl.')),
                ('beginn', models.DateField(default=datetime.date.today)),
                ('ende', models.DateField(default=datetime.date.today)),
                ('kurzbeschreibung', tinymce.models.HTMLField(verbose_name='Kurze Beschreibung')),
                ('beschreibung', tinymce.models.HTMLField(verbose_name='Beschreibung')),
                ('oeffentlich', models.BooleanField(default=True, verbose_name='Öffentliche Veranstaltung bzw. noch Plätze frei')),
                ('schlafplaetze', models.PositiveSmallIntegerField(default=0)),
                ('essensplaetze', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Veranstaltung',
                'verbose_name_plural': 'Veranstaltungen',
            },
        ),
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.CharField(choices=[('Frau', 'Frau'), ('Herr', 'Herr')], default='', max_length=15)),
                ('titel', models.CharField(blank=True, default='', max_length=15)),
                ('name', models.CharField(max_length=40)),
                ('vorname', models.CharField(max_length=40)),
                ('strasse', models.CharField(max_length=60, verbose_name='Straße und Hausnummer')),
                ('plz', models.CharField(max_length=8)),
                ('ort', models.CharField(max_length=40)),
                ('land', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('bemerkung', models.TextField(blank=True, default='')),
                ('anreisedatum', models.DateField(default=datetime.date.today)),
                ('abreisedatum', models.DateField(default=datetime.date.today)),
                ('businessaddress', models.BooleanField(default=False, verbose_name='Geschäftsadresse')),
                ('verpflegung', models.CharField(choices=[('Ich verpflege mich selbst', 'Ich verpflege mich selbst'), ('Ich nehme an der Verpflegung teil', 'Ich nehme an der Verpflegung teil'), ('Alles belegt. Ich möchte auf die Warteliste', 'Alles belegt. Ich möchte auf die Warteliste')], default='Ich verpflege mich selbst', max_length=43, verbose_name='Verpflegung')),
                ('unterbringung', models.CharField(choices=[('EXTERN', 'Ich wohne ausserhalb (Hotel o.ä.)'), ('ZELT', 'Ich schlafe im Zelt'), ('WOHNWAGEN', 'Ich komme mit dem Wohnwagen o.ä.'), ('IMHAUS', 'Ich brauche einen Schlafplatz im Haus'), ('WARTELISTE', 'Alles belegt. Ich möchte auf die Warteliste')], default='EXTERN', max_length=43, verbose_name='Unterbringung')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anmeldung.Event')),
            ],
            options={
                'verbose_name': 'Teilnehmer',
                'verbose_name_plural': 'Teilnehmer',
            },
        ),
        migrations.CreateModel(
            name='texte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bereich', models.CharField(choices=[('LEFT', 'linke Spalte'), ('RIGHT', 'rechte Spalte')], default='LEFT', max_length=5)),
                ('hoehe', models.CharField(choices=[('TOP', 'Über den Terminen'), ('BOTTOM', 'Unter den Terminen')], default='BOTTOM', max_length=6)),
                ('headertext', models.CharField(max_length=50, verbose_name='Überschrift')),
                ('langtext', tinymce.models.HTMLField(verbose_name='Text')),
                ('datepublishedstart', models.DateField(default=datetime.date.today, verbose_name='Veröffentlichung von')),
                ('datepublishedend', models.DateField(default=datetime.date.today, verbose_name='Veröffentlichung bis')),
            ],
            options={
                'verbose_name': 'Texte',
                'verbose_name_plural': 'Texte',
                'ordering': ['datepublishedstart'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senden', models.BooleanField(default=True, verbose_name='E-Mails senden')),
                ('emails_to', models.CharField(blank=True, max_length=60, null=True)),
                ('email_antworttext_teilnehmer', models.TextField(blank=True, default='', verbose_name='Text für aut. eMail-Antwort an Teilnehmer')),
                ('email_antworttext_organisation', models.TextField(blank=True, default='', verbose_name='Text für aut. eMail an Organisation bei neuer Anmeldung')),
            ],
            options={
                'verbose_name': 'System-Einstellung',
                'verbose_name_plural': 'System-Einstellungen',
            },
        ),
    ]
