# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 11:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=200)),
                ('bezeichnung_de', models.CharField(max_length=200, null=True)),
                ('bezeichnung_en', models.CharField(max_length=200, null=True)),
                ('bezeichnung_fr', models.CharField(max_length=200, null=True)),
                ('bezeichnung_el', models.CharField(max_length=200, null=True)),
                ('bezeichnung_pt', models.CharField(max_length=200, null=True)),
                ('registrationdeadline', models.DateField(default=datetime.date.today, verbose_name='Sichtbar bis einschl.')),
                ('beginn', models.DateField(default=datetime.date.today)),
                ('ende', models.DateField(default=datetime.date.today)),
                ('kurzbeschreibung', tinymce.models.HTMLField(verbose_name='Kurze Beschreibung')),
                ('kurzbeschreibung_de', tinymce.models.HTMLField(null=True, verbose_name='Kurze Beschreibung')),
                ('kurzbeschreibung_en', tinymce.models.HTMLField(null=True, verbose_name='Kurze Beschreibung')),
                ('kurzbeschreibung_fr', tinymce.models.HTMLField(null=True, verbose_name='Kurze Beschreibung')),
                ('kurzbeschreibung_el', tinymce.models.HTMLField(null=True, verbose_name='Kurze Beschreibung')),
                ('kurzbeschreibung_pt', tinymce.models.HTMLField(null=True, verbose_name='Kurze Beschreibung')),
                ('beschreibung', tinymce.models.HTMLField(verbose_name='Beschreibung')),
                ('beschreibung_de', tinymce.models.HTMLField(null=True, verbose_name='Beschreibung')),
                ('beschreibung_en', tinymce.models.HTMLField(null=True, verbose_name='Beschreibung')),
                ('beschreibung_fr', tinymce.models.HTMLField(null=True, verbose_name='Beschreibung')),
                ('beschreibung_el', tinymce.models.HTMLField(null=True, verbose_name='Beschreibung')),
                ('beschreibung_pt', tinymce.models.HTMLField(null=True, verbose_name='Beschreibung')),
                ('oeffentlich', models.BooleanField(default=True, verbose_name='Öffentliche Veranstaltung bzw. noch Plätze frei')),
                ('eventplaetze', models.PositiveSmallIntegerField(default=0, verbose_name='Plätze für Teilnehmer')),
                ('schlafplaetze', models.PositiveSmallIntegerField(default=0, verbose_name='Plätze für Übernachtung')),
                ('essensplaetze', models.PositiveSmallIntegerField(default=0, verbose_name='Plätze für Teilnehmer an der Verpflegung')),
            ],
            options={
                'verbose_name_plural': 'Veranstaltungen',
                'verbose_name': 'Veranstaltung',
            },
        ),
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.CharField(choices=[('Frau', 'Frau'), ('Herr', 'Herr')], default='', max_length=15, verbose_name='Anrede')),
                ('titel', models.CharField(blank=True, default='', max_length=15, verbose_name='Titel')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('vorname', models.CharField(max_length=40, verbose_name='Vorname')),
                ('strasse', models.CharField(max_length=60, verbose_name='Straße und Hausnummer')),
                ('plz', models.CharField(max_length=8, verbose_name='Postleitzahl')),
                ('ort', models.CharField(max_length=40, verbose_name='Ort')),
                ('land', models.CharField(blank=True, default='', max_length=40, verbose_name='Land')),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('bemerkung', models.TextField(blank=True, default='', verbose_name='Bemerkung')),
                ('anreisedatum', models.DateField(default=datetime.date.today, verbose_name='Anreisedatum')),
                ('abreisedatum', models.DateField(default=datetime.date.today, verbose_name='Abreisedatum')),
                ('verkehrsmittel', models.CharField(choices=[('BAHN', 'Ich fahre Bahn'), ('BAHNPICKUP', 'Ich fahre Bahn und möchte am Bahnhof abgeholt werden.'), ('AUTO', 'Ich komme mit dem Auto'), ('MITFAHRER', 'Ich bin Mitfahrer')], default='BAHN', max_length=40, verbose_name='Ich reise an mit')),
                ('mitfahrplaetze', models.PositiveSmallIntegerField(default=0, verbose_name='Ich biete Mitfahrgelegenheiten für')),
                ('businessaddress', models.BooleanField(default=False, verbose_name='Geschäftsadresse')),
                ('verpflegung', models.CharField(choices=[('Ich verpflege mich selbst', 'Ich verpflege mich selbst'), ('Ich nehme an der Verpflegung teil', 'Ich nehme an der Verpflegung teil'), ('Alles belegt. Ich möchte auf die Warteliste', 'Alles belegt. Ich möchte auf die Warteliste')], default='Ich verpflege mich selbst', max_length=43, verbose_name='Verpflegung')),
                ('unterbringung', models.CharField(choices=[('EXTERN', 'Ich wohne ausserhalb (Hotel o.ä.)'), ('ZELT', 'Ich schlafe im Zelt'), ('WOHNWAGEN', 'Ich komme mit dem Wohnwagen o.ä.'), ('IMHAUS', 'Ich brauche einen Schlafplatz im Haus'), ('WARTELISTE', 'Alles belegt. Ich möchte auf die Warteliste')], default='EXTERN', max_length=43, verbose_name='Unterbringung')),
                ('uebersetzung', models.BooleanField(default=False, verbose_name='Ich brauche eine Übersetzung')),
                ('uebersetzungen', models.CharField(choices=[('NONE', ' '), ('ENGLISH', 'I need an English translation'), ('FRENCH', "Jai besoin d'une traduction en français")], default='NONE', max_length=40, verbose_name='Art der Übersetzung')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anmeldung.Event')),
            ],
            options={
                'verbose_name_plural': 'Teilnehmer',
                'verbose_name': 'Teilnehmer',
            },
        ),
        migrations.CreateModel(
            name='texte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bereich', models.CharField(choices=[('LEFT', 'linke Spalte'), ('RIGHT', 'rechte Spalte')], default='LEFT', max_length=5)),
                ('hoehe', models.CharField(choices=[('TOP', 'Über den Terminen'), ('BOTTOM', 'Unter den Terminen')], default='BOTTOM', max_length=6)),
                ('headertext', models.CharField(max_length=50, verbose_name='Überschrift')),
                ('headertext_de', models.CharField(max_length=50, null=True, verbose_name='Überschrift')),
                ('headertext_en', models.CharField(max_length=50, null=True, verbose_name='Überschrift')),
                ('headertext_fr', models.CharField(max_length=50, null=True, verbose_name='Überschrift')),
                ('headertext_el', models.CharField(max_length=50, null=True, verbose_name='Überschrift')),
                ('headertext_pt', models.CharField(max_length=50, null=True, verbose_name='Überschrift')),
                ('langtext', tinymce.models.HTMLField(verbose_name='Text')),
                ('langtext_de', tinymce.models.HTMLField(null=True, verbose_name='Text')),
                ('langtext_en', tinymce.models.HTMLField(null=True, verbose_name='Text')),
                ('langtext_fr', tinymce.models.HTMLField(null=True, verbose_name='Text')),
                ('langtext_el', tinymce.models.HTMLField(null=True, verbose_name='Text')),
                ('langtext_pt', tinymce.models.HTMLField(null=True, verbose_name='Text')),
                ('datepublishedstart', models.DateField(default=datetime.date.today, verbose_name='Veröffentlichung am')),
                ('datepublishedend', models.DateField(default=datetime.date.today, verbose_name='Veröffentlichung bis')),
            ],
            options={
                'verbose_name_plural': 'Texte',
                'ordering': ['datepublishedstart'],
                'verbose_name': 'Texte',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senden', models.BooleanField(default=True, verbose_name='E-Mails senden')),
                ('emails_to', models.CharField(blank=True, max_length=60, null=True)),
                ('email_antworttext_teilnehmer', models.TextField(blank=True, default='', verbose_name='Text für aut. eMail-Antwort an Teilnehmer')),
                ('email_antworttext_organisation', models.TextField(blank=True, default='', verbose_name='Text für aut. eMail an Organisation bei neuer Anmeldung')),
            ],
            options={
                'verbose_name_plural': 'System-Einstellungen',
                'verbose_name': 'System-Einstellung',
            },
        ),
    ]
