# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teilnehmer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Anmeldung.Event'),
        ),
    ]
