# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0002_auto_20170301_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='beginn',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ende',
            field=models.DateField(null=True),
        ),
    ]
