# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0004_auto_20170302_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='beschreibung',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='abreise',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='anreise',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
