# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0005_auto_20170303_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teilnehmer',
            old_name='abreise',
            new_name='abreisedatum',
        ),
        migrations.RenameField(
            model_name='teilnehmer',
            old_name='anreise',
            new_name='anreisedatum',
        ),
    ]
