# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 11:19
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0006_auto_20170303_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='beschreibung',
            field=ckeditor.fields.RichTextField(default='Beschreibung'),
            preserve_default=False,
        ),
    ]
