# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0008_event_registration_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='registration_deadline',
            new_name='registrationdeadline',
        ),
    ]
