# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 17:15
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0009_auto_20170303_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kurzbeschreibung',
            field=ckeditor.fields.RichTextField(default='kurze Beschreibung'),
            preserve_default=False,
        ),
    ]
