# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0011_event_oeffentlich'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnehmer',
            name='anrede',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='bemerkung',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='land',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='telefon',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='titel',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='abreisedatum',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='anreisedatum',
            field=models.DateField(null=True),
        ),
    ]
