# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 10:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0012_auto_20170306_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='beschreibung',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
