# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0013_auto_20170306_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='beschreibung',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='oeffentlich',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='anrede',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='bemerkung',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='land',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='titel',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
