# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0015_texte'),
    ]

    operations = [
        migrations.AddField(
            model_name='texte',
            name='date_published',
            field=models.DateField(default=datetime.date.today, verbose_name='Veröffentlichung'),
        ),
        migrations.AlterField(
            model_name='texte',
            name='bereich',
            field=models.CharField(choices=[('LEFT', 'linke Spalte'), ('RIGHT',
                                                'rechte Spalte')], default='LEFT', max_length=5),
        ),
    ]
