# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0016_auto_20170307_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texte',
            old_name='date_published',
            new_name='datepublished',
        ),
    ]
