# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0019_auto_20170308_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bild_breite',
            field=models.IntegerField(null=True, verbose_name='Bild Breite (px)'),
        ),
        migrations.AddField(
            model_name='event',
            name='bild_hoehe',
            field=models.IntegerField(null=True, verbose_name='Bild Höhe (px)'),
        ),
    ]
