# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0020_auto_20170308_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to='bilder'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bild_breite',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bild Breite (px)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bild_hoehe',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bild Höhe (px)'),
        ),
    ]
