# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0021_auto_20170308_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teilnehmer',
            name='abreisedatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='anreisedatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
