# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0022_auto_20170308_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
