# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0024_auto_20170309_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bild_hoehe',
        ),
    ]
