# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0025_remove_event_bild_hoehe'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bild_hoehe',
            field=models.IntegerField(blank=True, default=150, null=True, verbose_name='Bild Höhe (px)'),
        ),
    ]
