# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0027_auto_20170309_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='bild_breite',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Bild Breite (px)'),
        ),
        migrations.AddField(
            model_name='event',
            name='bild_hoehe',
            field=models.IntegerField(blank=True, default=150, null=True, verbose_name='Bild Höhe (px)'),
        ),
    ]
