# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0028_auto_20170309_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bild_hoehe',
        ),
        migrations.AddField(
            model_name='texte',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='texte',
            name='bild_breite',
            field=models.IntegerField(blank=True, default=450, null=True, verbose_name='Bild Breite (px)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bild_breite',
            field=models.IntegerField(blank=True, default=450, null=True, verbose_name='Bild Breite (px)'),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
