# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0030_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='email_antworttext',
            field=models.TextField(blank=True, default='', verbose_name='Text für Antwort auf Anmeldung'),
        ),
    ]
