# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0031_usersettings_email_antworttext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'System-Einstellung', 'verbose_name_plural': 'System-Einstellungen'},
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='email_antworttext',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_antworttext_organisation',
            field=models.TextField(blank=True, default='', verbose_name='Text für aut. eMail an Organisation bei neuer Anmeldung'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_antworttext_teilnehmer',
            field=models.TextField(blank=True, default='', verbose_name='Text für aut. eMail-Antwort an Teilnehmer'),
        ),
    ]
