# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0032_auto_20170312_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='senden',
            field=models.BooleanField(default=True, verbose_name='E-Mails senden'),
        ),
    ]
