# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 07:20
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0033_usersettings_senden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='beschreibung',
            field=tinymce.models.HTMLField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kurzbeschreibung',
            field=tinymce.models.HTMLField(verbose_name='Kurze Beschreibung'),
        ),
        migrations.AlterField(
            model_name='texte',
            name='langtext',
            field=tinymce.models.HTMLField(verbose_name='Text'),
        ),
    ]
