# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anmeldung', '0034_auto_20170317_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texte',
            options={'ordering': ['datepublishedstart'], 'verbose_name': 'Texte', 'verbose_name_plural': 'Texte'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='bild',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bild_breite',
        ),
        migrations.RemoveField(
            model_name='texte',
            name='bild',
        ),
        migrations.RemoveField(
            model_name='texte',
            name='bild_breite',
        ),
        migrations.AddField(
            model_name='texte',
            name='hoehe',
            field=models.CharField(choices=[('TOP', 'Über den Terminen'), ('BOTTOM', 'Unter den Terminen')], default='BOTTOM', max_length=6),
        ),
    ]
